project:
  type: website
  output-dir: docs

website:
  bread-crumbs: true
  favicon: Logos/Logo_NoText.png
  title: "SPHERE-PPL"
  navbar:
    title: "SPHERE-PPL - VBD-HUB Training"
    logo: Logos/Logo_NoText.png
    tools:
      - icon: github
        href: https://github.com/SPHERE-PPL/VBD-Hub-Training
    right:
      - href: index.qmd
        text: Home
      - href: resources/biodiversity-modelling.qmd
        text: Handout
      - resources/code-example.qmd

        
  page-footer:
    border: true
    left: Copyright 2025 - SPHERE-PPL
    right:
      - text: "Spatial, Health & Environmental Research using Probilistic Programming Languages"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    page-layout: article
