---
title: "Temporal & Spatial Modelling of Disease Vectors"
---

## Overview

Welcome to the SPHERE-PPL training on Temporal & Spatial Modelling of Disease Vectors, first given at the VBD Hub Summer Workshop 2025. This page contains links to all of the material we will cover in the session and additional resources to supplement the learning!

## Key Outcomes

1.  Understand how to perform spatial and temporal analyses in R

2.  Explore the *`biomod2`* package

3.  Apply models to predict vector species distributions

## Lecture Notes

-   [Handout](resources/biodiversity-modelling.qmd)

-   [Getting Started Code](resources/code-example.qmd)

-   [Presentation slides](https://docs.google.com/presentation/d/1-_wCmO4gn6hE0CIipc21BFqB4rKgayaCACkZjUZOwIU/edit?usp=sharing)

## Resources

### Papers

**Standards for distribution models in biodiversity assessments (Araujo et al 2019 - Science Advances)**

-   [Main Paper](resources/Araujo_et_al_2019.pdf)

-   [Supplementary Material](resources/Araujo_et_al_2019-SM.pdf)

-   [Standards Table](resources/Ranking_Table.pdf)

**The merging of community ecology and phylogenetic biology (Cavender-Bares et al 2009 - Ecology Letters)**

-   [Paper](resources/Cavender-Bares-2009.pdf)

**Niches and distributional areas: Concepts, methods, and assumptions (Soberon & Nakamura - PNAS)**

-   [Paper](resources/Soberón-2009.pdf)

**Temporal validation plots: quantifying how well correlative species distribution models predict species' range changes over time**

-   [Paper](resources/Rapacciuolo-2014.pdf)

### Lyme Disease Forecasting Contest

-   [Getting Started](https://sphere-ppl.org/pages/Forecasting_Contests/)

-   [Contest Repo](https://github.com/SPHERE-PPL/HFC-Lyme-Disease)

## Instructors

-   Dr Will Pearse (Imperial) - [Website](https://pearselab.com/)

-   Dr Josh Tyler (Alan Turing Institute) - [Website](https://jtyler13.github.io/)

-   Nathan Clark (Imperial)
