---
title: "Spatial Analysis and Autocorrelation"
---

## Overview

As with time series analysis, it can be difficult to think of how we could collect data **outside** of space, so perhaps it's best to think of these techniques as important for data where your explanatory variables change across space. We will only be covering two-dimensional space in this lecture series, and it is very rare for biologists (or really any scientists) to need to control for spatial autocorrelation in a three-dimensional setting. Typically, if you have variation in height (elevation) in your data, this is fitted as an explanatory variable. Perhaps the only exception to this in a biological setting is marine data, and while I have only rarely seen studies of pelagic data that need to account for all three dimensions, in such cases the extension of these techniques (if not these precise packages) to such data is trivial. To begin with, we're going to extend the classic concept of correlation to account for **spatial** autocorrelation, which will give us a way to detect whether spatial autocorrelation exists in our datasets. We'll then cover two common methods for working with spatial data (autoregressive models and Generalized Least Squares (GLS) models), and then finish up with some hands-on experience working with spatial data.

## Detecting Spatial Autocorrelation

While we have spent a great deal of time in this course talking about the square of the correlation coefficient ($r^2$), but we have not considered its square-root in much detail. You have encountered the **correlation coefficient** in previous statistical classes, but let's review it here as we can detect spatial autocorrelation using an extension of it. The correlation coefficient, $r$, measures whether or not two vectors of data are correlated. There are many different definitions of it but, importantly, the **Pearson's correlation coefficient** we are focusing on today doesn't care which of them is the response or explanatory variable---they're all the same to it. It is defined as:

$$
r = \frac{\text{Outliers in x} \cdot \text{Outliers in y}}{\text{Variance in x and y}} = \frac{\sum((x - \bar{x})(y-\bar{y}))}{\sqrt{\sum(x-\bar{x})^2}\sqrt{\sum(y-\bar{y})^2}}
$$

Where $x$ and $y$ are the two variables we are testing for correlation, and $\bar{x}$ and $\bar{y}$ are the means of these two variables. The idea of a correlation test is to see whether values that are greater than the mean in one variable are paired with values that are above or below the mean in the other variable (that's our **observation**, and our **expectation** is they're not), in the context of how much background **variation** there is in the two variables[^1]. If there were lots of unusually large values in $x$ that were paired with unusually low values in $y$, we would tend to be multiplying lots of large positive values with lots of negative values, and would sum these up to get a very large negative value. This would be divided by the overall variation in the two variables, and we would get a negative number that was close to $-1$. The correlation coefficient can only range between $-1$ and $+1$: values closer to $-1$ mean there is a **negative** correlation between the values, values closer to $+1$ mean a positive value, and values closer to $0$ tend to mean there's little correlation between the variables.

[^1]: Surprise! It's another test statistic!

So how can we use this to measure the correlation of values **in the same variable** through space? Using something called **Moran's I**, which is remarkably similar to a Pearson's correlation coefficient, and is defined as:

$$
 I = \text{How many things} \cdot \frac{\text{Outliers here} \cdot \text{Outliers there}}{\text{Variation}} = \frac{n}{\sum w_{i,j}} \cdot \frac{\sum w_{i,j}(x_i-\bar{x})(x_j-\bar{x})}{\sum(x_i-\bar{x})^2}
$$

Where $x$ is our only variable, $\bar{x}$ is still the mean of $x$, $n$ is our number of data points, $w$ is a matrix (table) of **spatial weights** among the points and has dimensions $i$ (rows) and $j$ (columns) each corresponding to a particular observation of $x$ such that it has $n$ columns and $n$ rows. The spatial weights, $w$, are directly proportional to the **distances** among points: closer points are weighted higher (you can decide how much higher; see GLS below). Thus Moran's I is just the same, really, as a Pearson's correlation coefficient, only now instead of looking to see whether outliers in $x$ and $y$ are correlated, we're looking to see whether outliers in $x$ are in roughly the same area in space. In order to bring that concept of space into this, we need to weight our points according to how close they are, as otherwise we would simply be asking how correlated all points within a variable are with each other, which isn't useful for our purposes[^2]. There are two (equally fine) way to view the standardization term $\frac{n}{\sum w_{i,j}}$ in all of this: you can view it as dividing through by $\frac{\sum w_{i,j}}{n}$, in which case it's part of the **variance** component (take the overall variation in the weights matrix given how many points we have), or you can view it as you viewed the degrees of freedom in $F$-ratios, in which case we're (again) controlling for how many observations we have and also where they are in space. Either is fine.

[^2]: Indeed, it would just be the variance of x.

Moran's I values can be compared with an expected distribution of Moran's I values if there were no aggregation of similar values across space in exactly the same way as any other test statistics. It's quite common to generate a null distribution of I values through some kind of simulation procedure, however, because there's a dependence on the locations of your data points in space that can be tricky to solve analytically. Either way, the end result is the same: you get a distribution of expected Moran's I values, and you compare your observed value with that to find out what fraction of the distribution is greater than your observation[^3]. Note that you can also have spatial disaggregation: values of Moran's I that are less than $0$ and reflect points that are close to one-another in space being different from each other.

[^3]: If you have ever taken a course in bootstrapping, you might be a bit concerned that I've
      glossed over quite a lot of details about how to compare an observed
      value to a bootstrapped distribution. Yet you might also note that,
      from the definitions of frequentist distributions I gave you earlier
      in the class, frequentists treat probability as a set of
      observations in the long-run and so there's no difference really
      between bootstrapping and analytical expectations. If you haven't
      taken a class in bootstrapping, move on! Nothing to see
      here...

## Accounting for Spatial Autocorrelation

Imagine you've calculated Moran's I and it appears to be significantly different from zero: you've got spatial autocorrelation of some kind. Or, perhaps, you have a strong **a priori** reason to suppose you've got spatial autocorrelation and you don't want to test for it because you know it's there[^4]. What now? There is a huge body of literature devoted to modeling spatial data, and I'm going to present to you two reasonably straightforward methods for dealing with it. If you are interested, I cannot recommend Dormann *et al.* (2007) in *Ecography* highly enough. It's showing its age (it tests its models on a Pentium 4!), but the general concepts involved really haven't changed that much with the exception of recent focuses on Wavelet and spatial point-pattern analysis[^5].

[^4]: Good for you! You have been paying attention!

[^5]: Which really, truly are beyond the scope of this course, but I can point you in the direction of good introductions if you are interested.

### Simultaneous AutoRegressive Models

**Simultaneous AutoRegressive** models (SARs) are generalizations of the autoregressive models we met last time in a temporal context. The \`\`simultaneous'' component here accounts for the fact that we can regress the data against nearby values of the response variable, the explanatory variable, or both during model-fitting. You pick between those options depending on the kind of autocorrelation problem you think, or test to find, that you have. If you think the underlying variable that is driving the autocorrelation is in the explanatory variable (*e.g.*, temperature is driving mood but temperature is spatially autocorrelated) then you would regress your data against nearby temperature values. If you think it's in the response variable, (*e.g*., happy people make others around them happy), then you might regress against nearby response variables. If you're not sure... Go for both.

### Generalised Least Squares

We met **Generalized Least Squares** (GLS) models last time as a way to flexibly add any kind of ARIMA structure into a model. The good news is they can work in exactly the same way for spatial data. Where this can be useful is if you found the decision about what kind of SAR error structure to fit uncomfortable in the last section: with GLS, you have a bit more flexibility, and can also have autocorrelation in your *error* component. This is analogous to the decision we made in the time series session about whether we wanted to account for autocorrelation of the response variable (autoregressive models) or the error underlying the response variable (moving average models), although the specifics are a little different.

To work with GLS models, you need to specify the functional form of the autocorrelation you think is driving your data. For example, do you think there's an exponential (decaying) effect of space, where nearby points matter a lot and far away points matter very little? Then you can specify an *exponential* model of the form $e^{-\frac{a}{d}}$, where $e$ is the exponential function, $d$ is the *distance* among points, and $a$ is an estimated parameter that determines how fast the influence of nearby points decays. This is exactly analogous to the moving average models from last time, only now instead of an order (first, second, third, etc.) determining how many timesteps we \`\`listen'' to from earlier in the time series, now we have a continuous $d$istance and an amount we listen (the exponential function with its slope determined by $a$).

## Coda: Space isn't always time, and a statistical fix isn't always the right answer

I can't leave you without mentioning something that crops up a lot in my field: the modeling of space as if it were evolutionary time. A long time ago, in a galaxy far, far away, someone thought it would be a very good idea to account for correlation through time on a phylogenetic tree as if it were correlation through space \[see Diniz‐Filho *et al.* (1998) in Evolution\]. It was a very good idea, and under some circumstances it can be useful[^6], but in general it is absolutely not a good idea. This was definitively shown quite some time ago \[see Freckleton *et al.* (2011) in The American Naturalist\], but every now and again someone chances upon the idea of using some sort of spatial method in a new context. If you are going to use spatial methods for something that isn't space, do make sure they're mathematically simple to describe[^7], or else you will end up over-engineering something.

[^6]: See, for example, a paper I thought I would hate being involved with but that actually changed my mind on a lot of these eigenvector approaches; Morales‐Castilla et al. (2017) in Global Ecology and Biogeography.

[^7]: A single equation, with a handful of parameters, for the correlation structure.

Equally, and I might add that this applies to everything I have taught you in this course, do remember that **a statistical fix is no substitute for biological insight**. There are very few, if any, cases where having all of the important variables that drive a system in a model will go wrong in a straight-forward multiple regression. Everything else, from hierarchical models to spatial autocorrelation, is only needed if you don't have all the right information to hand. A good example of this is the Mantel test in spatial statistics, which I have deliberately not taught you because it can so easily lead to problems in spatial analyses \[see Legendre *et al.* (2015) in Methods in Ecology & Evolution---the answer to the title of their paper is no\]. Anything that cancels "out'' or "controls for'' something inevitably means that there is some process that is being ignored. Modeling spatial autocorrelation with a specific autoregressive or GLS function is notcanceling out'' the autocorrelation, it's measuring its impact. An even better thing to do, of course, would be to find out what is **driving** that autocorrelation and measure it.